# Generated by Django 3.2.7 on 2021-09-16 04:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('celular', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=255)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
